apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-application-service
spec:
  selector:
     project: {{ .Release.Name }}-web-application
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: {{ .Values.container.containerPort }}