name: Docker Image CI

on:
  push:
    branches: 
     - 'main'
  pull_request:
    branches:
     - 'main'

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: login to dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: build and push to dockerhub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/js:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/js:${{ github.run_number }}
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/js:buildcache
