name: Helm Deployment
on:
  workflow_dispatch:

jobs:
 helm-deployment:
   runs-on: ubuntu-latest

   steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install helm
      uses: azure/setup-helm@v1
      with:
         version: v3.8.1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Update kube config
      run: aws eks update-kubeconfig --name terraform-eks-kubernetes-new --region ${{ secrets.AWS_REGION }}

    - name: Run helm files
      run: |
        helm upgrade --install app-js helm/
