name: Kubernetes Deployment
on:
  workflow_dispatch:

jobs:
 kubernetes-deployment:
   runs-on: ubuntu-latest

   steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.24.3'
      id: install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Update kube config
      run: aws eks update-kubeconfig --name terraform-eks-kubernetes-new --region ${{ secrets.AWS_REGION }}


    - name: Install ingress
      run: |
        kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.2.0/deploy/static/provider/cloud/deploy.yaml

    - name: Update kube config
      run: |
        kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission


    - name: Run kubernetes files
      run: |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
        kubectl apply -f kubernetes/ingress.yaml


