name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  terraform-apply:
    name: terraform-apply
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    env:	
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: ./test
        id: init
        run: |
           terraform init
        
      - name: Terraform Plan
        id: plan
        working-directory: ./test
        run: |
          terraform plan -no-color
        continue-on-error: true


      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        working-directory: ./test
        run: |
          exit 1

      - name: Terraform Apply
        id: apply
        working-directory: ./test
        run: |
          terraform apply -auto-approve